"""
1. The code imports two modules, "pandas" and "get_column_letter" from "openpyxl.utils".
2. It defines a function called "top_geographic_score" that reads data from a CSV file named "trips.csv".
3. The function filters data from the CSV file to select successful primary trips during the morning rush hour,
calculates the number of trips by ZIP code, selects the top 10 ZIP codes with the most trips, and writes the results
to a new Excel file named "SUMMARY_OUTPUTS.xlsx".
4. The function also handles any errors that may occur during the data processing and formatting and ignores any
warnings generated by the code.
5. The function uses an ExcelWriter object to write data to an existing Excel file or create a new one.
It checks if the sheet named "question_3" already exists in the workbook, removes it if it does, and writes the
new data to the sheet. It also adjusts the width of the second column of the sheet to make the data easier to read.
"""

import pandas as pd
from openpyxl.utils import get_column_letter
import warnings

def top_geographic_score():
    # read the trips.csv file into a pandas dataframe
    trips_df = pd.read_csv('trips.csv')

    # filter for successful "Primary" trips during AM rush hour
    am_rush_hour_df = trips_df[(trips_df['Status'] == 'S') & 
                            (trips_df['ProviderType'] == 'Primary') & 
                            (trips_df['PromiseTime'].str[:2].astype(int) >= 6) &
                            (trips_df['PromiseTime'].str[:2].astype(int) <= 10)]

    warnings.filterwarnings("error")

    try:
        # extract the first 5 digits of the pickup ZIP codes
        am_rush_hour_df.loc[:, 'PickupZip'] = am_rush_hour_df['PickZip'].str[:5]
    except Exception as ex:
        pass

    # count the number of trips by pickup ZIP code
    zip_counts = am_rush_hour_df['PickupZip'].value_counts().reset_index()

    # rename the columns of the zip_counts dataframe
    zip_counts.columns = ['ZIP code', 'Number of Primary trips during AM rush hour']

    # limit the zip_counts dataframe to the top 10 ZIP codes
    top_10_zip_counts = zip_counts.nlargest(10, columns='Number of Primary trips during AM rush hour')

    with pd.ExcelWriter('SUMMARY_OUTPUTS.xlsx', engine='openpyxl', mode='a') as writer:
        try:
            if 'question_3' in writer.book.sheetnames:
                # If the sheet already exists, remove it
                writer.book.remove(writer.book.sheetnames.index('question_3'))
                # Add the sheet with the modified dataframe
            top_10_zip_counts.to_excel(writer, sheet_name='question_3', index=False, header=True)
            worksheet = writer.sheets['question_3']
            worksheet.column_dimensions[get_column_letter(2)].width = worksheet.column_dimensions[get_column_letter(2)].width * 3 
        except:
            pass
    warnings.filterwarnings("ignore")